server {
    listen 80;
    listen [::]:80;
    listen 5174;
    listen [::]:5174;
    server_name test.ybxylazycats.dpdns.org;

    root /vol1/1panel/www/sites/test.ybxylazycats.dpdns.org/index;
    index index.html;

    # API 代理
    location ^~ /api {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 主工具站
    location = / {
        try_files /index.html =404;
    }

    # Package Repo
    location = /repo {
        try_files /repo/index.html =404;
    }

    # 闲鱼水印工具
    location = /fish {
        try_files /fish/index.html =404;
    }

    # 安全规则
    location ~ ^/\.htaccess {
        return 403;
    }

    location ^~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }

    error_page 404 /404.html;
    real_ip_recursive on;
    set_real_ip_from 127.0.0.1;
    real_ip_header X-Real-IP;
}
